# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-04-29 00:05
from __future__ import unicode_literals

import autoslug.fields
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('chiton_runway', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='FormalityExpectation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('frequency', models.CharField(choices=[('never', 'Never'), ('rarely', 'Occasionally'), ('sometimes', '1-2 times per week'), ('often', '3-4 times per week'), ('always', '5+ times per week')], max_length=25, verbose_name='frequency')),
                ('formality', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='chiton_runway.Formality', verbose_name='level of formality')),
            ],
            options={
                'verbose_name': 'formality expectation',
                'verbose_name_plural': 'formality expectations',
            },
        ),
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=255, verbose_name='first name')),
                ('last_name', models.CharField(max_length=255, verbose_name='last name')),
                ('slug', autoslug.fields.AutoSlugField(editable=False, max_length=255, populate_from='first_name', unique=True, verbose_name='slug')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='user')),
            ],
            options={
                'verbose_name': 'person',
                'ordering': ('last_name', 'first_name'),
                'verbose_name_plural': 'people',
            },
        ),
        migrations.CreateModel(
            name='WardrobeProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('shape', models.CharField(choices=[('pear', 'Pear'), ('hourglass', 'Hourglass'), ('inverted', 'Inverted triangle'), ('apple', 'Apple'), ('rectangle', 'Rectangle')], max_length=25, verbose_name='body shape')),
                ('age', models.PositiveSmallIntegerField(verbose_name='age')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
                ('person', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='chiton_wintour.Person', verbose_name='person')),
                ('styles', models.ManyToManyField(to='chiton_runway.Style', verbose_name='styles')),
            ],
            options={
                'verbose_name': 'wardrobe profile',
                'verbose_name_plural': 'wardrobe profiles',
            },
        ),
        migrations.AddField(
            model_name='formalityexpectation',
            name='profile',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='expectations', to='chiton_wintour.WardrobeProfile', verbose_name='wardrobe profile'),
        ),
    ]
