# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-05-05 23:53
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chiton_wintour', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='wardrobeprofile',
            old_name='shape',
            new_name='body_shape',
        ),
    ]
