# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-05-20 01:12
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('chiton_wintour', '0003_wardrobeprofile_sizes'),
    ]

    operations = [
        migrations.CreateModel(
            name='UnwantedCareType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('care', models.CharField(choices=[('machine_machine', 'Machine wash and dry'), ('machine_air', 'Machine wash, air dry'), ('hand_wash', 'Hand wash'), ('dry_clean', 'Dry clean')], max_length=25, verbose_name='care instructions')),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='unwanted_care_types', to='chiton_wintour.WardrobeProfile', verbose_name='wardrobe profile')),
            ],
            options={
                'verbose_name': 'unwanted care type',
                'verbose_name_plural': 'unwanted care types',
            },
        ),
    ]
