# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-05-22 00:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chiton_closet', '0016_auto_20160522_0039'),
        ('chiton_wintour', '0005_remove_wardrobeprofile_sizes'),
    ]

    operations = [
        migrations.AddField(
            model_name='wardrobeprofile',
            name='sizes',
            field=models.ManyToManyField(to='chiton_closet.StandardSize', verbose_name='sizes'),
        ),
    ]
