# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-07-09 00:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chiton_wintour', '0007_recommendation'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='wardrobeprofile',
            name='age',
        ),
        migrations.AddField(
            model_name='wardrobeprofile',
            name='birth_year',
            field=models.PositiveSmallIntegerField(default=1980, verbose_name='birth year'),
            preserve_default=False,
        ),
    ]
