# -*- coding: utf-8 -*-
# Generated by Django 1.9.9 on 2016-08-22 14:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chiton_wintour', '0008_auto_20160709_0008'),
    ]

    operations = [
        migrations.AddField(
            model_name='recommendation',
            name='ip_address',
            field=models.GenericIPAddressField(blank=True, null=True, verbose_name='IP address'),
        ),
    ]
