# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-08-31 23:34
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chiton_wintour', '0010_remove_person_slug'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='person',
            name='user',
        ),
    ]
