# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-09-02 14:14
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('chiton_wintour', '0013_person_encrypted_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='person',
            name='joined',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='joined'),
            preserve_default=False,
        ),
    ]
