# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-05-12 16:44
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('chiton_rack', '0004_affiliateitem_price'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductImage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('height', models.PositiveIntegerField(verbose_name='height')),
                ('width', models.PositiveIntegerField(verbose_name='width')),
                ('url', models.URLField(verbose_name='URL')),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='chiton_rack.AffiliateItem', verbose_name='affiliate item')),
            ],
            options={
                'verbose_name': 'product image',
                'verbose_name_plural': 'product images',
            },
        ),
        migrations.AddField(
            model_name='affiliateitem',
            name='image',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='image_for', to='chiton_rack.ProductImage', verbose_name='image'),
        ),
        migrations.AddField(
            model_name='affiliateitem',
            name='thumbnail',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='thumbnail_for', to='chiton_rack.ProductImage', verbose_name='thumbnail'),
        ),
    ]
