# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-05-12 17:12
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chiton_rack', '0005_auto_20160512_1644'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productimage',
            name='item',
        ),
    ]
