# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-05-22 00:44
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('chiton_closet', '0016_auto_20160522_0039'),
        ('chiton_rack', '0008_auto_20160522_0043'),
    ]

    operations = [
        migrations.CreateModel(
            name='StockRecord',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_available', models.BooleanField(default=False, verbose_name='is available')),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stock_records', to='chiton_rack.AffiliateItem', verbose_name='affiliate item')),
                ('size', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='chiton_closet.StandardSize', verbose_name='size')),
            ],
            options={
                'verbose_name': 'stock record',
                'verbose_name_plural': 'stock records',
            },
        ),
    ]
