# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-06-04 01:34
from __future__ import unicode_literals

from django.db import migrations
from django.db.models import Count


def remove_duplicate_items(apps, schema_editor):
    """Remove affiliate items that are duplicated by GUID and network."""
    AffiliateItem = apps.get_model('chiton_rack', 'AffiliateItem')

    duplicates = (
        AffiliateItem.objects
        .values('guid', 'network')
        .annotate(guids=Count('guid'), networks=Count('network'))
        .filter(guids__gt=1, networks__gt=1)
    )

    for duplicate in duplicates:
        items = AffiliateItem.objects.filter(guid=duplicate['guid'], network_id=duplicate['network'])
        for index, item in enumerate(items):
            if not index:
                continue
            item.delete()


class Migration(migrations.Migration):

    dependencies = [
        ('chiton_rack', '0010_auto_20160525_0005'),
    ]

    operations = [
        migrations.RunPython(remove_duplicate_items)
    ]
