# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-06-08 01:18
from __future__ import unicode_literals

import chiton.closet.model_fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chiton_rack', '0012_auto_20160604_0150'),
    ]

    operations = [
        migrations.AlterField(
            model_name='affiliateitem',
            name='price',
            field=chiton.closet.model_fields.PriceField(blank=True, db_index=True, decimal_places=2, max_digits=8, null=True, verbose_name='price'),
        ),
    ]
