# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-06-15 01:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chiton_rack', '0013_auto_20160608_0118'),
    ]

    operations = [
        migrations.AddField(
            model_name='affiliateitem',
            name='has_detailed_stock',
            field=models.BooleanField(default=False, verbose_name='has detailed stock'),
        ),
    ]
