# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-11 20:05
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chiton_rack', '0015_auto_20160711_1937'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productimage',
            name='file',
            field=models.ImageField(blank=True, height_field='height', null=True, upload_to='products', verbose_name='file', width_field='width'),
        ),
    ]
