# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-11 23:30
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('chiton_rack', '0016_auto_20160711_2005'),
    ]

    operations = [
        migrations.CreateModel(
            name='ItemImage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.ImageField(blank=True, height_field='height', null=True, upload_to='products', verbose_name='file', width_field='width')),
                ('height', models.PositiveIntegerField(verbose_name='height')),
                ('width', models.PositiveIntegerField(verbose_name='width')),
            ],
            options={
                'verbose_name': 'item image',
                'verbose_name_plural': 'item images',
            },
        ),
        migrations.RemoveField(
            model_name='affiliateitem',
            name='image',
        ),
        migrations.RemoveField(
            model_name='affiliateitem',
            name='thumbnail',
        ),
        migrations.DeleteModel(
            name='ProductImage',
        ),
        migrations.AddField(
            model_name='itemimage',
            name='item',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='chiton_rack.AffiliateItem', verbose_name='affiliate item'),
        ),
    ]
