# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-12 00:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chiton_rack', '0017_auto_20160711_2330'),
    ]

    operations = [
        migrations.AddField(
            model_name='itemimage',
            name='source_url',
            field=models.URLField(default='', verbose_name='source URL'),
            preserve_default=False,
        ),
    ]
