# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-13 00:34
from __future__ import unicode_literals

import chiton.rack.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chiton_rack', '0017_auto_20160712_0101'),
    ]

    operations = [
        migrations.AlterField(
            model_name='itemimage',
            name='file',
            field=models.ImageField(height_field='height', upload_to=chiton.rack.models._upload_path_for_item_image, verbose_name='file', width_field='width'),
        ),
    ]
