# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-13 01:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chiton_rack', '0018_auto_20160713_0034'),
    ]

    operations = [
        migrations.AddField(
            model_name='affiliateitem',
            name='retailer',
            field=models.CharField(db_index=True, default='Unknown', max_length=255, verbose_name='retailer'),
            preserve_default=False,
        ),
    ]
