# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-09-06 00:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chiton_rack', '0020_affiliateitem_affiliate_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='affiliateitem',
            name='has_multiple_colors',
            field=models.BooleanField(default=False, verbose_name='has multiple colors'),
        ),
    ]
