# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-05-12 17:20
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('chiton_runway', '0002_auto_20160505_2353'),
    ]

    operations = [
        migrations.AlterField(
            model_name='basic',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='chiton_runway.Category', verbose_name='category'),
        ),
    ]
