# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-05-12 17:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chiton_closet', '0007_auto_20160508_1729'),
        ('chiton_runway', '0003_auto_20160512_1720'),
    ]

    operations = [
        migrations.AddField(
            model_name='basic',
            name='colors',
            field=models.ManyToManyField(to='chiton_closet.Color', verbose_name='colors'),
        ),
    ]
