# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-05-26 23:39
from __future__ import unicode_literals

import chiton.closet.model_fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chiton_runway', '0008_auto_20160525_0009'),
    ]

    operations = [
        migrations.AlterField(
            model_name='basic',
            name='budget_end',
            field=chiton.closet.model_fields.PriceField(blank=True, decimal_places=2, default=0, max_digits=8, null=True, verbose_name='budget end price'),
        ),
        migrations.AlterField(
            model_name='basic',
            name='luxury_start',
            field=chiton.closet.model_fields.PriceField(blank=True, decimal_places=2, default=0, max_digits=8, null=True, verbose_name='luxury start price'),
        ),
    ]
