# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-05-26 23:44
from __future__ import unicode_literals

from django.db import migrations


def set_basic_price_defaults(apps, schema_editor):
    """Set all Basic price points to zero."""
    Basic = apps.get_model('chiton_runway', 'Basic')
    for basic in Basic.objects.all():
        basic.budget_end = 0
        basic.luxury_start = 0
        basic.save()


class Migration(migrations.Migration):

    dependencies = [
        ('chiton_runway', '0009_auto_20160526_2339'),
    ]

    operations = [
        migrations.RunPython(set_basic_price_defaults)
    ]
