# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-08-02 10:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chiton_runway', '0012_auto_20160802_1029'),
    ]

    operations = [
        migrations.AddField(
            model_name='basic',
            name='plural_name',
            field=models.CharField(default='Default', max_length=255, verbose_name='plural name'),
            preserve_default=False,
        ),
    ]
