# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-08-05 00:06
from __future__ import unicode_literals

from django.db import migrations


def merge_shells(apps, schema_editor):
    """Merge black and white shells into one basic."""
    Basic = apps.get_model('chiton_runway', 'Basic')
    Garment = apps.get_model('chiton_closet', 'Garment')

    white_shell = Basic.objects.get(slug='white-shell')
    black_shell = Basic.objects.get(slug='black-shell')

    for garment in Garment.objects.filter(basic=black_shell):
        garment.basic = white_shell
        garment.save()

    black_shell.delete()

    white_shell.name = 'Shell'
    white_shell.save()


class Migration(migrations.Migration):

    dependencies = [
        ('chiton_runway', '0013_basic_plural_name'),
    ]

    operations = [
        migrations.RunPython(merge_shells)
    ]
