# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-02-24 00:56
from __future__ import unicode_literals

import autoslug.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Brand',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='name')),
                ('slug', autoslug.fields.AutoSlugField(editable=False, max_length=255, populate_from='name', unique=True, verbose_name='slug')),
                ('url', models.URLField(blank=True, max_length=255, null=True, verbose_name='URL')),
            ],
            options={
                'verbose_name': 'brand',
                'verbose_name_plural': 'brands',
            },
        ),
        migrations.CreateModel(
            name='Garment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='name')),
                ('slug', autoslug.fields.AutoSlugField(editable=False, max_length=255, populate_from='name', unique=True, verbose_name='slug')),
                ('brand', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='chiton_closet.Brand', verbose_name='brand')),
            ],
            options={
                'verbose_name': 'garment',
                'verbose_name_plural': 'garments',
            },
        ),
        migrations.CreateModel(
            name='GarmentCategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='name')),
                ('slug', autoslug.fields.AutoSlugField(editable=False, max_length=255, populate_from='name', unique=True, verbose_name='slug')),
            ],
            options={
                'verbose_name': 'garment category',
                'verbose_name_plural': 'garment categories',
            },
        ),
        migrations.CreateModel(
            name='GarmentOption',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='name')),
                ('slug', autoslug.fields.AutoSlugField(editable=False, max_length=255, populate_from='name', unique=True, verbose_name='slug')),
            ],
            options={
                'verbose_name': 'garment option',
                'verbose_name_plural': 'garment options',
            },
        ),
        migrations.AddField(
            model_name='garment',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='chiton_closet.GarmentCategory', verbose_name='category'),
        ),
    ]
