# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-03-05 02:11
from __future__ import unicode_literals

import autoslug.fields
import chiton.closet.model_fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Brand',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=255, verbose_name='name')),
                ('slug', autoslug.fields.AutoSlugField(editable=False, max_length=255, populate_from='name', unique=True, verbose_name='slug')),
                ('age_lower', models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='lower target age')),
                ('age_upper', models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='upper target age')),
            ],
            options={
                'verbose_name': 'brand',
                'ordering': ('name',),
                'verbose_name_plural': 'brands',
            },
        ),
        migrations.CreateModel(
            name='Formality',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=255, verbose_name='name')),
                ('slug', autoslug.fields.AutoSlugField(editable=False, max_length=255, populate_from='name', unique=True, verbose_name='slug')),
                ('position', models.PositiveSmallIntegerField(default=0, verbose_name='position')),
            ],
            options={
                'verbose_name': 'level of formality',
                'ordering': ('position',),
                'verbose_name_plural': 'levels of formality',
            },
        ),
        migrations.CreateModel(
            name='Garment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=255, verbose_name='name')),
                ('slug', autoslug.fields.AutoSlugField(editable=False, max_length=255, populate_from='name', unique=True, verbose_name='slug')),
                ('shoulder_emphasis', chiton.closet.model_fields.EmphasisField(choices=[(-1, 'Weak'), (0, 'Neutral'), (1, 'Strong')], default=0, verbose_name='shoulder emphasis')),
                ('waist_emphasis', chiton.closet.model_fields.EmphasisField(choices=[(-1, 'Weak'), (0, 'Neutral'), (1, 'Strong')], default=0, verbose_name='waist emphasis')),
                ('hip_emphasis', chiton.closet.model_fields.EmphasisField(choices=[(-1, 'Weak'), (0, 'Neutral'), (1, 'Strong')], default=0, verbose_name='hip emphasis')),
                ('sleeve_length', models.CharField(choices=[('tank', 'Tank'), ('short', 'Short'), ('3/4', '3/4'), ('long', 'Long')], max_length=15, null=True, verbose_name='sleeve length')),
                ('bottom_length', models.CharField(choices=[('short', 'Short'), ('knee', 'Knee'), ('3/4', '3/4'), ('ankle', 'Ankle'), ('long', 'Long')], max_length=15, null=True, verbose_name='bottom length')),
                ('pant_rise', models.CharField(choices=[('low', 'Low'), ('normal', 'Normal'), ('high', 'High')], max_length=15, null=True, verbose_name='pant rise')),
                ('description', models.TextField(blank=True, help_text='A public description', null=True, verbose_name='description')),
                ('notes', models.TextField(blank=True, help_text='Internal information', null=True, verbose_name='notes')),
                ('is_busty', models.BooleanField(default=False, verbose_name='is for busty women')),
                ('brand', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='chiton_closet.Brand', verbose_name='brand')),
                ('formalities', models.ManyToManyField(to='chiton_closet.Formality', verbose_name='levels of formality')),
            ],
            options={
                'verbose_name': 'garment',
                'verbose_name_plural': 'garments',
            },
        ),
        migrations.CreateModel(
            name='Style',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True, verbose_name='name')),
                ('slug', autoslug.fields.AutoSlugField(editable=False, max_length=255, populate_from='name', unique=True, verbose_name='slug')),
            ],
            options={
                'verbose_name': 'style',
                'ordering': ('name',),
                'verbose_name_plural': 'styles',
            },
        ),
        migrations.AddField(
            model_name='garment',
            name='styles',
            field=models.ManyToManyField(to='chiton_closet.Style', verbose_name='styles'),
        ),
    ]
