# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-03-13 23:35
from __future__ import unicode_literals

import autoslug.fields
import chiton.closet.model_fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('chiton_runway', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Brand',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=255, verbose_name='name')),
                ('slug', autoslug.fields.AutoSlugField(editable=False, max_length=255, populate_from='name', unique=True, verbose_name='slug')),
                ('age_lower', models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='lower target age')),
                ('age_upper', models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='upper target age')),
            ],
            options={
                'ordering': ('name',),
                'verbose_name': 'brand',
                'verbose_name_plural': 'brands',
            },
        ),
        migrations.CreateModel(
            name='Garment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=255, verbose_name='name')),
                ('slug', autoslug.fields.AutoSlugField(editable=False, max_length=255, populate_from='name', unique=True, verbose_name='slug')),
                ('shoulder_emphasis', chiton.closet.model_fields.EmphasisField(choices=[(-1, 'Weak'), (0, 'Neutral'), (1, 'Strong')], default=0, verbose_name='shoulder emphasis')),
                ('waist_emphasis', chiton.closet.model_fields.EmphasisField(choices=[(-1, 'Weak'), (0, 'Neutral'), (1, 'Strong')], default=0, verbose_name='waist emphasis')),
                ('hip_emphasis', chiton.closet.model_fields.EmphasisField(choices=[(-1, 'Weak'), (0, 'Neutral'), (1, 'Strong')], default=0, verbose_name='hip emphasis')),
                ('sleeve_length', models.CharField(blank=True, choices=[('tank', 'Tank'), ('short', 'Short'), ('3/4', '3/4'), ('long', 'Long')], max_length=15, null=True, verbose_name='sleeve length')),
                ('bottom_length', models.CharField(blank=True, choices=[('short', 'Short'), ('knee', 'Knee'), ('3/4', '3/4'), ('ankle', 'Ankle'), ('long', 'Long')], max_length=15, null=True, verbose_name='bottom length')),
                ('pant_rise', models.CharField(blank=True, choices=[('low', 'Low'), ('normal', 'Normal'), ('high', 'High')], max_length=15, null=True, verbose_name='pant rise')),
                ('description', models.TextField(blank=True, help_text='A public description', null=True, verbose_name='description')),
                ('notes', models.TextField(blank=True, help_text='Internal information', null=True, verbose_name='notes')),
                ('is_busty', models.NullBooleanField(verbose_name='is for busty women')),
                ('brand', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='chiton_closet.Brand', verbose_name='brand')),
                ('formalities', models.ManyToManyField(to='chiton_runway.Formality', verbose_name='levels of formality')),
                ('styles', models.ManyToManyField(to='chiton_runway.Style', verbose_name='styles')),
            ],
            options={
                'verbose_name': 'garment',
                'verbose_name_plural': 'garments',
            },
        ),
    ]
