# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-02-19 01:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chiton_closet', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='brand',
            name='url',
            field=models.URLField(blank=True, max_length=255, null=True, verbose_name='URL'),
        ),
    ]
