# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-04-28 23:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chiton_closet', '0002_garment_is_plus_sized'),
    ]

    operations = [
        migrations.AddField(
            model_name='garment',
            name='care',
            field=models.CharField(blank=True, choices=[('machine_machine', 'Machine wash and dry'), ('machine_air', 'Machine wash, air dry'), ('hand_wash', 'Hand wash'), ('dry_clean', 'Dry clean')], max_length=25, null=True, verbose_name='care instructions'),
        ),
    ]
