# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-05-07 17:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chiton_closet', '0004_auto_20160428_2350'),
    ]

    operations = [
        migrations.AddField(
            model_name='garment',
            name='is_featured',
            field=models.BooleanField(default=False, verbose_name='is featured'),
        ),
    ]
