# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-05-16 17:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chiton_closet', '0007_auto_20160508_1729'),
    ]

    operations = [
        migrations.RenameField(
            model_name='size',
            old_name='base',
            new_name='name'
        ),
        migrations.AlterField(
            model_name='size',
            name='name',
            field=models.CharField(choices=[('xxs', 'XXS'), ('xs', 'XS'), ('s', 'S'), ('m', 'M'), ('l', 'L'), ('xl', 'XL'), ('xxl', 'XXL'), ('plus1', 'Plus 1X'), ('plus2', 'Plus 2X'), ('plus3', 'Plus 3X'), ('plus4', 'Plus 4X'), ('plus5', 'Plus 5X')], max_length=15, verbose_name='name'),
        )
    ]
