# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-05-20 01:04
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chiton_closet', '0009_auto_20160516_1732'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='size',
            unique_together=set([]),
        ),
    ]
