# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-05-21 17:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chiton_closet', '0010_auto_20160520_0104'),
    ]

    operations = [
        migrations.AddField(
            model_name='garment',
            name='is_petite_sized',
            field=models.BooleanField(default=False, verbose_name='is available in petite sizes'),
        ),
        migrations.AddField(
            model_name='garment',
            name='is_regular_sized',
            field=models.BooleanField(default=True, verbose_name='is available in regular sizes'),
        ),
        migrations.AddField(
            model_name='garment',
            name='is_tall_sized',
            field=models.BooleanField(default=False, verbose_name='is available in tall sizes'),
        ),
        migrations.AlterField(
            model_name='garment',
            name='is_plus_sized',
            field=models.BooleanField(default=False, verbose_name='is available in plus sizes'),
        ),
    ]
