# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-05-21 17:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chiton_closet', '0011_auto_20160521_1720'),
    ]

    operations = [
        migrations.AddField(
            model_name='size',
            name='is_plus_sized',
            field=models.BooleanField(default=False, verbose_name='is plus-sized'),
        ),
    ]
