# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-05-21 19:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chiton_closet', '0013_auto_20160521_1918'),
    ]

    operations = [
        migrations.AlterField(
            model_name='size',
            name='name',
            field=models.CharField(choices=[('XXS', 'XXS'), ('XS', 'XS'), ('S', 'S'), ('M', 'M'), ('L', 'L'), ('XL', 'XL'), ('XXL', 'XXL'), ('Plus 1X', 'Plus 1X'), ('Plus 2X', 'Plus 2X'), ('Plus 3X', 'Plus 3X'), ('Plus 4X', 'Plus 4X'), ('Plus 5X', 'Plus 5X')], max_length=25, verbose_name='name'),
        ),
    ]
