# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-05-21 19:42
from __future__ import unicode_literals

import autoslug.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chiton_closet', '0014_auto_20160521_1928'),
    ]

    operations = [
        migrations.AlterField(
            model_name='size',
            name='slug',
            field=autoslug.fields.AutoSlugField(editable=False, max_length=255, populate_from='name', unique=True, verbose_name='slug'),
        ),
    ]
