# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-05-22 00:39
from __future__ import unicode_literals

import autoslug.fields
import chiton.closet.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('chiton_wintour', '0005_remove_wardrobeprofile_sizes'),
        ('chiton_rack', '0007_remove_stockrecord_size'),
        ('chiton_closet', '0015_auto_20160521_1942'),
    ]

    operations = [
        migrations.CreateModel(
            name='CanonicalSize',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[('XXS', 'XXS'), ('XS', 'XS'), ('S', 'S'), ('M', 'M'), ('L', 'L'), ('XL', 'XL'), ('XXL', 'XXL'), ('Plus 1X', 'Plus 1X'), ('Plus 2X', 'Plus 2X'), ('Plus 3X', 'Plus 3X'), ('Plus 4X', 'Plus 4X'), ('Plus 5X', 'Plus 5X')], max_length=25, unique=True, verbose_name='name')),
                ('slug', autoslug.fields.AutoSlugField(editable=False, max_length=255, populate_from='name', unique=True, verbose_name='slug')),
                ('range_lower', models.PositiveSmallIntegerField(verbose_name='lower numeric size')),
                ('range_upper', models.PositiveSmallIntegerField(verbose_name='upper numeric size')),
                ('is_plus_sized', models.BooleanField(default=False, verbose_name='is plus-sized')),
                ('position', models.PositiveSmallIntegerField(default=0, verbose_name='position')),
            ],
            options={
                'verbose_name': 'canonical size',
                'verbose_name_plural': 'canonical sizes',
                'ordering': ('position',),
            },
        ),
        migrations.CreateModel(
            name='StandardSize',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', autoslug.fields.AutoSlugField(editable=False, max_length=255, populate_from=chiton.closet.models._make_slug_for_standard_size, unique=True, verbose_name='slug')),
                ('is_tall', models.BooleanField(default=False, verbose_name='tall')),
                ('is_petite', models.BooleanField(default=False, verbose_name='petite')),
                ('position', models.PositiveSmallIntegerField(default=0, verbose_name='position')),
                ('canonical', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='chiton_closet.CanonicalSize', verbose_name='canonical size')),
            ],
            options={
                'verbose_name': 'standard size',
                'verbose_name_plural': 'standard sizes',
                'ordering': ('position',),
            },
        ),
        migrations.DeleteModel(
            name='Size',
        ),
        migrations.AlterUniqueTogether(
            name='standardsize',
            unique_together=set([('canonical', 'is_tall', 'is_petite')]),
        ),
    ]
