# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-05-22 01:12
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chiton_closet', '0016_auto_20160522_0039'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='canonicalsize',
            unique_together=set([('name', 'range_lower', 'range_upper', 'is_plus_sized')]),
        ),
    ]
