# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-05-22 17:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chiton_closet', '0017_auto_20160522_0112'),
    ]

    operations = [
        migrations.AddField(
            model_name='standardsize',
            name='is_plus_sized',
            field=models.BooleanField(default=False, verbose_name='plus-sized'),
        ),
        migrations.AddField(
            model_name='standardsize',
            name='is_regular',
            field=models.BooleanField(default=True, verbose_name='regular'),
        ),
        migrations.AlterField(
            model_name='canonicalsize',
            name='name',
            field=models.CharField(choices=[('XXS', 'XXS'), ('XS', 'XS'), ('S', 'S'), ('M', 'M'), ('L', 'L'), ('XL', 'XL'), ('XXL', 'XXL'), ('1X', '1X'), ('2X', '2X'), ('3X', '3X'), ('4X', '4X'), ('5X', '5X')], max_length=25, unique=True, verbose_name='name'),
        ),
        migrations.AlterUniqueTogether(
            name='canonicalsize',
            unique_together=set([('name', 'range_lower', 'range_upper')]),
        ),
        migrations.RemoveField(
            model_name='canonicalsize',
            name='is_plus_sized',
        ),
        migrations.AlterUniqueTogether(
            name='standardsize',
            unique_together=set([('canonical', 'is_tall', 'is_petite', 'is_regular', 'is_plus_sized')]),
        ),
    ]
