# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-05-29 00:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chiton_closet', '0018_auto_20160522_1758'),
    ]

    operations = [
        migrations.AlterField(
            model_name='brand',
            name='age_lower',
            field=models.PositiveSmallIntegerField(default=0, verbose_name='lower target age'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='brand',
            name='age_upper',
            field=models.PositiveSmallIntegerField(default=0, verbose_name='upper target age'),
            preserve_default=False,
        ),
    ]
